apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: dev-test
  labels:
    app: nginx-server
    version: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
      version: alpha
  template:
    metadata:
      name: nginx-server
      labels:
        app: nginx-server
        version: alpha
    spec:
      containers:
      - name: nginx-server
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  namespace: dev-test
  labels:
    app: nginx-server
    version: alpha
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32565
  selector:
    app: nginx-server
    version: alpha
    
    
   
 
  
