apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-server
  namespace: dev-test
  labels:
    app: login-server
    version: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-server
      version: alpha
  template:
    metadata:
      name: login-server
      labels:
        app: login-server
        version: alpha
    spec:
      containers:
      - name: login-server
        image: 44.200.219.148:8082/loginimg:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: nexus-cred
       
---

apiVersion: v1
kind: Service
metadata:
  name: login-server
  namespace: dev-test
  labels:
    app: login-server
    version: alpha
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32565
  selector:
    app: login-server
    version: alpha
    
    
   
 
 
